"""
CONFIG V1 — FROZEN BASELINE
=============================
Locked after the validated ticker run (ticker_validation_results.csv,
12 Aug 2026). Do not edit this file to chase better backtest numbers —
if a change is warranted, create config_v2.py and compare results
against this file's frozen output, don't overwrite it.
"""

# ---------------------------------------------------------------------------
# DRIVER TICKERS
# name -> (yfinance ticker, role, first_available_date, notes)
# first_available_date is taken directly from the validated CSV, not
# assumed. PRIMARY = used in hypotheses. FALLBACK = confirmation-only,
# never silently substituted for a PRIMARY.
# ---------------------------------------------------------------------------
DRIVERS = {
    "sp500":        ("^GSPC",    "PRIMARY", "1927-12-30", "one 12-day gap in raw series — gap-null protection applies"),
    "nasdaq":       ("^IXIC",    "PRIMARY", "1971-02-05", None),
    "dow":          ("^DJI",     "PRIMARY", "1992-01-02", None),
    "russell2000":  ("^RUT",     "PRIMARY", "1987-09-10", None),
    "vix":          ("^VIX",     "PRIMARY", "1990-01-02", None),
    "xle":          ("XLE",      "PRIMARY", "1998-12-22", None),
    "xlf":          ("XLF",      "PRIMARY", "1998-12-22", None),
    "xlv":          ("XLV",      "PRIMARY", "1998-12-22", None),
    "xly":          ("XLY",      "PRIMARY", "1998-12-22", None),
    "xlp":          ("XLP",      "PRIMARY", "1998-12-22", None),
    "xli":          ("XLI",      "PRIMARY", "1998-12-22", None),
    "xlk":          ("XLK",      "PRIMARY", "1998-12-22", None),
    "xlre":         ("XLRE",     "PRIMARY", "2015-10-08", None),
    "xlu":          ("XLU",      "PRIMARY", "1998-12-22", None),
    "xlc":          ("XLC",      "PRIMARY", "2018-06-19", None),
    "wti":          ("CL=F",     "PRIMARY", "2000-08-23", None),
    "brent":        ("BZ=F",     "PRIMARY", "2007-07-30", "one 17-day gap in raw series — gap-null protection applies"),
    "natgas":       ("NG=F",     "PRIMARY", "2000-08-30", None),
    "gold":         ("GC=F",     "PRIMARY", "2000-08-30", None),
    "silver":       ("SI=F",     "PRIMARY", "2000-08-30", None),
    "copper":       ("HG=F",     "PRIMARY", "2000-08-30", None),
    "iron_ore":     ("TIO=F",    "PRIMARY", "2010-10-14", "confirmed clean, no proxy substitution needed"),
    "vale_adr":     ("VALE",     "FALLBACK", "2002-03-21", "iron ore confirmation only"),
    "cliffs":       ("CLF",      "FALLBACK", "1973-02-21", "iron ore confirmation only"),
    "lit":          ("LIT",      "PRIMARY", "2010-07-23", None),
    "albemarle":    ("ALB",      "PRIMARY", "1994-02-22", "lithium confirmation, deeper history than LIT"),
    "sqm":          ("SQM",      "PRIMARY", "1993-09-21", "lithium confirmation, deeper history than LIT"),
    "ura":          ("URA",      "PRIMARY", "2010-11-05", None),
    "cameco":       ("CCJ",      "PRIMARY", "1996-03-14", "uranium confirmation, deeper history than URA"),
    "uec":          ("UEC",      "PRIMARY", "2007-04-05", None),
    "coal":         ("BTU",      "PRIMARY", "2017-04-03", None),
    "audusd":       ("AUDUSD=X", "PRIMARY", "2006-05-16", None),
    "dxy":          ("DX-Y.NYB", "PRIMARY", "1971-01-04", None),
    "bhp_adr":      ("BHP",      "PRIMARY", "1980-03-17", None),
    "rio_adr":      ("RIO",      "PRIMARY", "1990-06-28", None),
    "gdx":          ("GDX",      "PRIMARY", "2006-05-22", None),
    "newmont":      ("NEM",      "PRIMARY", "1980-03-17", None),
}
# DX=F confirmed EMPTY on Yahoo — deliberately excluded, not a fallback.

# ---------------------------------------------------------------------------
# ASX THEME -> STOCK BASKETS
# Unchanged from the live overnight scanner (ASX_THEME_STOCKS) — reused
# as-is rather than reinvented, per "smallest architecture change."
# ---------------------------------------------------------------------------
ASX_THEME_STOCKS = {
    "Gold": ["NST.AX", "EVN.AX", "NEM.AX", "RRL.AX", "GOR.AX"],
    "Lithium": ["PLS.AX", "MIN.AX", "IGO.AX", "LTR.AX"],
    "Uranium": ["PDN.AX", "BOE.AX", "DYL.AX"],
    "Copper": ["SFR.AX", "29M.AX"],
    "Rare Earths": ["LYC.AX", "ILU.AX", "ARU.AX"],
    "Iron Ore": ["BHP.AX", "RIO.AX", "FMG.AX", "MIN.AX", "CIA.AX"],
    "Coal": ["WHC.AX", "YAL.AX", "NHC.AX"],
    "Energy (Oil/Gas)": ["WDS.AX", "STO.AX", "KAR.AX", "BPT.AX"],
    "Financials (Banks)": ["CBA.AX", "WBC.AX", "NAB.AX", "ANZ.AX", "MQG.AX"],
}

# ---------------------------------------------------------------------------
# PER-THEME DRIVER WEIGHTS (default; per-stock overrides can be added
# later once real results show which stocks behave differently to their
# theme average — starting theme-level, not stock-level, per "smallest
# architecture change")
# ---------------------------------------------------------------------------
THEME_DRIVER_WEIGHTS = {
    "Energy (Oil/Gas)": {"brent": 3, "wti": 2.5, "xle": 2, "sp500": 0.5, "nasdaq": 0.2, "audusd": 0.5, "vix": 0.5},
    "Gold": {"gold": 3, "gdx": 2.5, "audusd": 1, "sp500": 0.3, "vix": 0.5},
    "Lithium": {"lit": 3, "nasdaq": 1, "sp500": 0.5, "vix": 0.5},
    "Iron Ore": {"iron_ore": 3, "bhp_adr": 2, "rio_adr": 1.5, "sp500": 0.5, "audusd": 0.5},
    "Financials (Banks)": {"sp500": 2, "xlf": 2, "vix": 1, "audusd": 0.3},
    "Uranium": {"ura": 3, "cameco": 1.5, "uec": 1, "sp500": 0.3},
    "Coal": {"coal": 2.5, "sp500": 0.5, "audusd": 0.3},
}

# ---------------------------------------------------------------------------
# THE FIRST FIVE HYPOTHESES
# Each condition function takes a row of the driver table (a dict/Series
# of % moves keyed by driver name) and returns True/False.
# usable_from is the max() of first_available_date across the drivers
# used — computed from the table above, not eyeballed.
# ---------------------------------------------------------------------------
def _long_short_pair(id_base, label_base, theme, drivers_used, usable_from, cond_long, cond_short):
    """LONG and SHORT are each their own independently-matched historical
    sample (different trigger, different set of days) — NOT a sign-flip
    of one sample pretending to be two. A failed LONG relationship does
    not imply anything about the SHORT one; both get evaluated on their
    own matched days."""
    return [
        {"id": f"{id_base}_long", "label": f"{label_base} (LONG)", "theme": theme,
         "direction": "LONG", "drivers_used": drivers_used, "usable_from": usable_from,
         "condition": cond_long},
        {"id": f"{id_base}_short", "label": f"{label_base} (SHORT)", "theme": theme,
         "direction": "SHORT", "drivers_used": drivers_used, "usable_from": usable_from,
         "condition": cond_short},
    ]


HYPOTHESES = []

HYPOTHESES += _long_short_pair(
    "H1", "Brent +-2% -> ASX Energy basket", "Energy (Oil/Gas)", ["brent"], "2007-07-30",
    cond_long=lambda row: row.get("brent", float("nan")) > 2.0,
    cond_short=lambda row: row.get("brent", float("nan")) < -2.0,
)
HYPOTHESES += _long_short_pair(
    "H1b", "Brent +-2% AND US Energy ETF (XLE) confirming -> ASX Energy basket",
    "Energy (Oil/Gas)", ["brent", "xle"], "2007-07-30",
    cond_long=lambda row: row.get("brent", float("nan")) > 2.0 and row.get("xle", float("nan")) > 1.0,
    cond_short=lambda row: row.get("brent", float("nan")) < -2.0 and row.get("xle", float("nan")) < -1.0,
)
HYPOTHESES += _long_short_pair(
    "H2", "Gold +-2% -> ASX Gold basket", "Gold", ["gold"], "2006-05-22",  # capped to GDX start, comparable to H2b
    cond_long=lambda row: row.get("gold", float("nan")) > 2.0,
    cond_short=lambda row: row.get("gold", float("nan")) < -2.0,
)
HYPOTHESES += _long_short_pair(
    "H2b", "Gold +-2% AND US Gold Miners (GDX) confirming -> ASX Gold basket",
    "Gold", ["gold", "gdx"], "2006-05-22",
    cond_long=lambda row: row.get("gold", float("nan")) > 2.0 and row.get("gdx", float("nan")) > 2.0,
    cond_short=lambda row: row.get("gold", float("nan")) < -2.0 and row.get("gdx", float("nan")) < -2.0,
)
HYPOTHESES += _long_short_pair(
    "H3", "Lithium (LIT) +-3% -> ASX Lithium basket", "Lithium", ["lit"], "2010-07-23",
    cond_long=lambda row: row.get("lit", float("nan")) > 3.0,
    cond_short=lambda row: row.get("lit", float("nan")) < -3.0,
)
HYPOTHESES += _long_short_pair(
    "H3b", "Nasdaq weak/strong AND Lithium (LIT) diverging -> ASX Lithium basket",
    "Lithium", ["nasdaq", "lit"], "2010-07-23",
    cond_long=lambda row: row.get("nasdaq", float("nan")) < -1.0 and row.get("lit", float("nan")) > 2.0,
    cond_short=lambda row: row.get("nasdaq", float("nan")) > 1.0 and row.get("lit", float("nan")) < -2.0,
)
HYPOTHESES += _long_short_pair(
    "H4", "Iron Ore (TIO=F) +-1% -> ASX Iron Ore basket", "Iron Ore", ["iron_ore"], "2010-10-14",
    cond_long=lambda row: row.get("iron_ore", float("nan")) > 1.0,
    cond_short=lambda row: row.get("iron_ore", float("nan")) < -1.0,
)
HYPOTHESES += _long_short_pair(
    "H4b", "Iron Ore +-1% AND BHP ADR confirming -> ASX Iron Ore basket",
    "Iron Ore", ["iron_ore", "bhp_adr"], "2010-10-14",
    cond_long=lambda row: row.get("iron_ore", float("nan")) > 1.0 and row.get("bhp_adr", float("nan")) > 1.0,
    cond_short=lambda row: row.get("iron_ore", float("nan")) < -1.0 and row.get("bhp_adr", float("nan")) < -1.0,
)
HYPOTHESES += _long_short_pair(
    "H5", "S&P500 +-1% -> ASX Financials basket (baseline/control)",
    "Financials (Banks)", ["sp500"], "1990-01-02",  # sane modern-market start; ASX financials history confirmed on first pull
    cond_long=lambda row: row.get("sp500", float("nan")) > 1.0,
    cond_short=lambda row: row.get("sp500", float("nan")) < -1.0,
)
# H1/H2/H3/H4 are deliberately paired (alone vs confirmed) so the backtest
# directly answers "does requiring a second confirming driver actually
# help, or just shrink the sample for no benefit." Every hypothesis is
# also paired LONG vs SHORT as two independently-matched samples, per
# the brief — 18 hypotheses total in this V1 baseline.

# ---------------------------------------------------------------------------
# OPENING GAP BUCKETS (direction-adjusted: computed against the trade's
# own direction, not raw sign, so a SHORT setup's "favourable" gap is a
# negative one)
# ---------------------------------------------------------------------------
GAP_BUCKETS = [
    ("against_signal", float("-inf"), 0.0),
    ("small_favourable", 0.0, 1.0),
    ("moderate_favourable", 1.0, 2.0),
    ("large_favourable", 2.0, 3.0),
    ("very_large_favourable", 3.0, float("inf")),
]

# ---------------------------------------------------------------------------
# COSTS — kept as two separate, explicit numbers. Slippage defaults to 0
# and is clearly an unset assumption, not a modelled estimate.
# ---------------------------------------------------------------------------
COSTS = {
    "commission_bps_roundtrip": 5,   # confirmed by user
    "slippage_bps_roundtrip": 0,     # UNSET — not modelled, flagged in output
}

# ---------------------------------------------------------------------------
# SAMPLE SIZE BANDS        
# ---------------------------------------------------------------------------
SAMPLE_SIZE_BANDS = [
    (0, 20, "insufficient", "Not shown as an edge — informational only"),
    (20, 50, "early_signal", "Shown as hypothesis, not a claimed edge"),
    (50, 100, "emerging", "Shown with confidence interval, moderate confidence"),
    (100, float("inf"), "workable", "Reportable, still shown with confidence interval"),
]

# ---------------------------------------------------------------------------
# CHRONOLOGICAL TRAIN / VALIDATION / TEST SPLIT
# Computed per-hypothesis against its own usable_from date, not a single
# global date range.
# ---------------------------------------------------------------------------
SPLIT_RATIOS = {"train": 0.6, "validation": 0.2, "test": 0.2}

# Raw-series gap beyond which a computed 1-day return is nulled rather
# than trusted (catches the S&P 12-day hole and Brent 17-day hole
# automatically, and any future undiscovered ones).
PER_OBSERVATION_GAP_NULL_THRESHOLD_DAYS = 6
